### ISSUE TITLE
Add Funcionality when app is in Background

### ISSUE THREAD

**Issue by UO247134** [Arquisoft/radarin_es1a#74]
- [ ] Update Ubication of User
- [ ] Send notifications (Mobile phone too)

**Comment by UO247134** [comment]
### Solutions:
- https://stackoverflow.com/questions/37767307/push-notifications-if-app-is-closed-react-native

**Comment by UO266618** [comment]
The iOS operating system, in 2021, implements service worker that previously did not. The problem is that they do not have the notifications API that is being used in this application.

- https://stackoverflow.com/questions/43994660/push-notifications-on-ios-from-web-app
- https://www.google.com/amp/s/www.izooto.com/blog/ios-safari-push-notifications-in-2021%3fhs_amp=true
